stages: 
- sonar

#=================== Sonar Stage ===================
.sonar_template: &sonar_definition
  stage: sonar
  tags:
    - msbuild
  before_script:
    - set SONAR_SCANNER_OPTS="%SONAR_SCANNER_OPTS%"
    - |
      set SONAR_SONARQUBE_REPORT=^
        /k:"%CI_PROJECT_PATH_SLUG%" ^
        /n:"%CI_PROJECT_PATH%" ^
        /d:sonar.host.url="%SONAR_HOST_URL%" ^
        /d:sonar.login="%SONAR_AUTH_TOKEN%" ^
        /d:sonar.verbose=true
    - |
      set SONAR_GATEGIT_REPORT=^
      /d:sonar.analysis.mode=preview ^
      /d:sonar.gitlab.commit_sha="%CI_COMMIT_SHA%" ^
      /d:sonar.gitlab.ref_name="%CI_COMMIT_REF_NAME%" ^
      /d:sonar.gitlab.project_id="%CI_PROJECT_ID%"
  script:
    - |
      "%GenerateSln%" -batchmode -nographics -quit ^
        -projectPath %cd% ^
        -CacheServerIPAddress "%UNITY_CACHE_SERVER%" ^
        -logFile GenerateSln.log ^
        -executeMethod SonarUnity.GenerateSln
    - |
      IF "%REPORT_ENV%"=="sonar-gategit-report" (
        "%SONAR_MSBUILD_HOME%\%SONAR_MSBUILD_VER%\SonarScanner.MSBuild" begin %SONAR_SONARQUBE_REPORT% %SONAR_GATEGIT_REPORT%
      )
    - |
      IF "%REPORT_ENV%"=="sonar-sonarqube-report" (
        "%SONAR_MSBUILD_HOME%\%SONAR_MSBUILD_VER%\SonarScanner.MSBuild" begin %SONAR_SONARQUBE_REPORT%
      )
    - MSBuild "%UNITY_SLN_NAME%".sln /t:Rebuild
    - |
      "%SONAR_MSBUILD_HOME%\%SONAR_MSBUILD_VER%\SonarScanner.MSBuild" end ^
        /d:sonar.login="%SONAR_AUTH_TOKEN%"
    - echo "%REPORT_ENV% DONE"

.sonar-artifacts_template:
  artifacts: &sonar_artifacts_definition
    name: "sonar-GenerateSln-artifact"
    paths:
      - GenerateSln.log
    expire_in: 1 week

sonar_gategit:
  <<: *sonar_definition
  variables:
    REPORT_ENV: "sonar-gategit-report"
  only:
    - branches
  artifacts: *sonar_artifacts_definition

sonar_sonarqube:
  <<: *sonar_definition
  variables:
    REPORT_ENV: "sonar-sonarqube-report"
  only:
    - master
  artifacts: *sonar_artifacts_definition
